const MOBILEVIEW=()=>{
  const LOADDATA={
    home: () => {SHYLANSIRAJANDROIDSTARTPAGE();},
  };
  LINKTRACKER(LOADDATA,()=>{
    WEBMAINSTARTPAGE();
  });
};
const DESKTOPVIEW=()=>{
  const LOADDATA={
    home: () => {SHYLANSIRAJANDROIDSTARTPAGE();},
  };
  LINKTRACKER(LOADDATA,()=>{
    WEBMAINSTARTPAGE();
  });
};
VIEW(()=>{MOBILEVIEW();},()=>{DESKTOPVIEW()});